
language: c
compiler: arm-none-eabi-gcc

services: docker

install:
  - docker build https://github.com/bolthur/build-tools.git#develop -t bolthur-build-tools

script:
  - docker run --privileged -v $TRAVIS_BUILD_DIR:/src bolthur-build-tools /src/.travis-ci/build.sh

notifications:
  email: false
