
language: c

addons:
  apt:
    update: true
    packages:
      - gcc
      - g++

cache:
  directories:
    - /home/travis/.bolthur

install:
  - mkdir -p /home/travis/.bolthur/cross
  - git clone https://github.com/bolthur/bootstrap.git
  - pushd .
  - cd bootstrap
  - ./toolchain-build.sh -p /home/travis/.bolthur
  - popd

before_script:
  - export PATH="/home/travis/.bolthur/cross/bin:$PATH"
  - arm-unknown-bolthur-eabi-gcc --version
  - autoconf --version
  - cppcheck --version

notifications:
  email: false

stages:
  - compile

jobs:
  include:
    - stage: compile
      compiler: arm-unknown-bolthur-eabi-gcc
      name: "RPI 2 rev. 1 - debug"
      script:
        - autoreconf -iv
        - mkdir -p build/rpi2_rev1_debug
        - cd build/rpi2_rev1_debug
        - ../../configure --enable-silent-rules --host arm-none-eabi --enable-device=rpi2_b_rev1 --with-debug-symbols --enable-output --enable-output-mm-phys --enable-output-mm-virt --enable-output-mm-heap --enable-output-mailbox --enable-output-timer --enable-output-initrd --enable-output-event --enable-output-process --enable-output-interrupt --enable-output-exception --enable-output-elf --enable-output-platform --enable-output-syscall --enable-output-serial --enable-remote-debug
        - make cppcheck
        - make all
    - stage: compile
      compiler: arm-unknown-bolthur-eabi-gcc
      name: "RPI 2 rev. 1 - prod"
      script:
        - autoreconf -iv
        - mkdir -p build/rpi2_rev1_release
        - cd build/rpi2_rev1_release
        - ../../configure --enable-silent-rules --host arm-none-eabi --enable-device=rpi2_b_rev1
        - make cppcheck
        - make all
